inclusion_criteria:
  demographics:                     # Optional
    gender: 'female'                # accepted values: female or male, optional field
    min_birth_year: 2000            # Born at the year of 2000 or after, optional field
    max_birth_year: 2020            # Born at the year of 2020 or before, optional field
