root_omop_cdm_database:
  database_type: duckdb
  username: dummy
  password: dummy
  hostname: dummy
  database: /Users/sherrylu/Documents/UNC/26Fall/VAC Lab/BiasAnalyzerYAMLBuilder/data/synpuf_100k_omop_54.duckdb
  port: 5432