# example configuration for BiasAnalyzer

root_omop_cdm_database:
  invalid_database_type: duckdb   # set it to one of the two supported types: postgresql or duckdb
  invalid_username: test_username
  password: test_password
  hostname: test_db_hostname
  port: unsupported
